name: random_toolkit
description: 一个功能强大的Flutter随机数据生成工具包，提供各种类型的随机数据生成功能。
version: 0.0.7
homepage: https://gitee.com/peiduo_734386/random_toolkit
repository: https://gitee.com/peiduo_734386/random_toolkit.git
issue_tracker: https://gitee.com/peiduo_734386/random_toolkit/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# 纯Dart包，无需插件配置
